using System.ComponentModel.DataAnnotations;

namespace AutoCare.Models;
public class LoginVm { [Required,EmailAddress] public string Email { get; set; }=""; [Required,DataType(DataType.Password)] public string Password { get; set; }=""; [Display(Name="Security answer")] public string CaptchaAnswer { get; set; }=""; }
public class RegisterVm { [Required,StringLength(80)] public string FullName { get; set; }=""; [Required,EmailAddress] public string Email { get; set; }=""; [Required,Phone] public string Phone { get; set; }=""; [Required,StringLength(100,MinimumLength=8),DataType(DataType.Password)] public string Password { get; set; }=""; [Compare(nameof(Password)),DataType(DataType.Password)] public string ConfirmPassword { get; set; }=""; }
public class AppointmentVm { [Required] public int VehicleId { get;set; } [Required] public int WorkshopServiceId { get;set; } [Required,DataType(DataType.DateTime)] public DateTime AppointmentAt { get;set; }=DateTime.Today.AddDays(1).AddHours(9); [Required,StringLength(800,MinimumLength=10)] public string ProblemDescription { get;set; }=""; }
public class VerifyEmailVm { [Required,EmailAddress] public string Email { get;set; }=""; [Required,StringLength(6,MinimumLength=6)] public string Otp { get;set; }=""; }
public class ForgotPasswordVm { [Required,EmailAddress] public string Email { get;set; }=""; }
public class ResetPasswordVm { [Required,EmailAddress] public string Email { get;set; }=""; [Required,StringLength(6,MinimumLength=6)] public string Otp { get;set; }=""; [Required,StringLength(100,MinimumLength=8),DataType(DataType.Password)] public string NewPassword { get;set; }=""; [Compare(nameof(NewPassword)),DataType(DataType.Password)] public string ConfirmPassword { get;set; }=""; }
public class ChangePasswordVm { [Required,DataType(DataType.Password)] public string CurrentPassword { get;set; }=""; [Required,StringLength(100,MinimumLength=8),DataType(DataType.Password)] public string NewPassword { get;set; }=""; [Compare(nameof(NewPassword)),DataType(DataType.Password)] public string ConfirmPassword { get;set; }=""; }
public class ProfileVm { [Required,StringLength(80)] public string FullName { get;set; }=""; [Required,Phone] public string Phone { get;set; }=""; [StringLength(20)] public string ThemePreference { get;set; }="light"; [StringLength(10)] public string LanguagePreference { get;set; }="en"; public string? ProfilePhotoPath { get;set; } }
public class ChatPageVm { public ChatThread? SelectedThread { get; set; } public List<ChatThread> Threads { get; set; } = new(); public bool IsAdmin { get; set; } }
